version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: yarn run test-expressions
      - store_artifacts:
          path: /tmp/test/integration/expression-tests/index.html
      - run: yarn run test-unit
      - run: yarn run build-prod && yarn deploy
