version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    working_directory: ~/mapbox-gl-js
    steps:
      - checkout
      - run: yarn
      - run: yarn run test-expressions
      - store_artifacts:
          path: test/integration/expression-tests/index.html
          destination: artifact-file
      - run: yarn run lint
      - run: yarn run test-unit
